language: python

os:
  - linux
  - osx
python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.5-dev'
  - '3.6'
  - '3.6-dev'
  - '3.7-dev'
  - 'nightly'
install:
  - pip install -e .
script:
  - ./test_all.sh
